language: c

env: HOW_DOC=tutos HOW_CONFIG=how.json HOW_OUT=_doc 

install: 
    - wget https://ocsigen.org/how.sh
    - . how.sh
    - how-install

script:
    - how-generate
    - how-redirect "$HOW_LATEST/manual/intro" $HOW_OUT/index.html
    - mkdir -p $HOW_OUT/latest/manual && how-redirect-manual 2.6 latest

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GHP_TOKEN
  local-dir: _doc
  on:
    branch: master
